# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import turbo_pb2 as turbo__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in turbo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TurboStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Maintain = channel.unary_unary(
                '/turbo.Turbo/Maintain',
                request_serializer=turbo__pb2.MaintainReq.SerializeToString,
                response_deserializer=turbo__pb2.MaintainResp.FromString,
                _registered_method=True)


class TurboServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Maintain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TurboServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Maintain': grpc.unary_unary_rpc_method_handler(
                    servicer.Maintain,
                    request_deserializer=turbo__pb2.MaintainReq.FromString,
                    response_serializer=turbo__pb2.MaintainResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'turbo.Turbo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('turbo.Turbo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Turbo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Maintain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turbo.Turbo/Maintain',
            turbo__pb2.MaintainReq.SerializeToString,
            turbo__pb2.MaintainResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
