// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: proto/src/turbo/turbo.proto

package turbo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Turbo_Maintain_FullMethodName = "/turbo.Turbo/Maintain"
)

// TurboClient is the client API for Turbo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TurboClient interface {
	Maintain(ctx context.Context, in *MaintainReq, opts ...grpc.CallOption) (*MaintainResp, error)
}

type turboClient struct {
	cc grpc.ClientConnInterface
}

func NewTurboClient(cc grpc.ClientConnInterface) TurboClient {
	return &turboClient{cc}
}

func (c *turboClient) Maintain(ctx context.Context, in *MaintainReq, opts ...grpc.CallOption) (*MaintainResp, error) {
	out := new(MaintainResp)
	err := c.cc.Invoke(ctx, Turbo_Maintain_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TurboServer is the server API for Turbo service.
// All implementations must embed UnimplementedTurboServer
// for forward compatibility
type TurboServer interface {
	Maintain(context.Context, *MaintainReq) (*MaintainResp, error)
	mustEmbedUnimplementedTurboServer()
}

// UnimplementedTurboServer must be embedded to have forward compatible implementations.
type UnimplementedTurboServer struct {
}

func (UnimplementedTurboServer) Maintain(context.Context, *MaintainReq) (*MaintainResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Maintain not implemented")
}
func (UnimplementedTurboServer) mustEmbedUnimplementedTurboServer() {}

// UnsafeTurboServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TurboServer will
// result in compilation errors.
type UnsafeTurboServer interface {
	mustEmbedUnimplementedTurboServer()
}

func RegisterTurboServer(s grpc.ServiceRegistrar, srv TurboServer) {
	s.RegisterService(&Turbo_ServiceDesc, srv)
}

func _Turbo_Maintain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaintainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboServer).Maintain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Turbo_Maintain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboServer).Maintain(ctx, req.(*MaintainReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Turbo_ServiceDesc is the grpc.ServiceDesc for Turbo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Turbo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "turbo.Turbo",
	HandlerType: (*TurboServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Maintain",
			Handler:    _Turbo_Maintain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/src/turbo/turbo.proto",
}
