// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.14.0
// source: proto/src/turbo/turbo.proto

package turbo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaintainReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// provides all kind of secrets for accessing data from source
	// please deploy this service with TLS, for not transfering in plain text.
	Secrets map[string][]byte `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tasks   []*PreLoadTask    `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *MaintainReq) Reset() {
	*x = MaintainReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_src_turbo_turbo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaintainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintainReq) ProtoMessage() {}

func (x *MaintainReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_turbo_turbo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintainReq.ProtoReflect.Descriptor instead.
func (*MaintainReq) Descriptor() ([]byte, []int) {
	return file_proto_src_turbo_turbo_proto_rawDescGZIP(), []int{0}
}

func (x *MaintainReq) GetSecrets() map[string][]byte {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *MaintainReq) GetTasks() []*PreLoadTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type PreLoadTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StackId uint64 `protobuf:"varint,1,opt,name=stack_id,json=stackId,proto3" json:"stack_id,omitempty"`
	// stack_size is sum of data_size, index_size and meta_size
	StackSize uint64 `protobuf:"varint,2,opt,name=stack_size,json=stackSize,proto3" json:"stack_size,omitempty"`
	// source_path is all kind of source that this dataset placed.
	SourcePath []string `protobuf:"bytes,3,rep,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
}

func (x *PreLoadTask) Reset() {
	*x = PreLoadTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_src_turbo_turbo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreLoadTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreLoadTask) ProtoMessage() {}

func (x *PreLoadTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_turbo_turbo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreLoadTask.ProtoReflect.Descriptor instead.
func (*PreLoadTask) Descriptor() ([]byte, []int) {
	return file_proto_src_turbo_turbo_proto_rawDescGZIP(), []int{1}
}

func (x *PreLoadTask) GetStackId() uint64 {
	if x != nil {
		return x.StackId
	}
	return 0
}

func (x *PreLoadTask) GetStackSize() uint64 {
	if x != nil {
		return x.StackSize
	}
	return 0
}

func (x *PreLoadTask) GetSourcePath() []string {
	if x != nil {
		return x.SourcePath
	}
	return nil
}

type PreLoadTaskStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StackId    uint64 `protobuf:"varint,1,opt,name=stack_id,json=stackId,proto3" json:"stack_id,omitempty"`
	StackSize  uint64 `protobuf:"varint,2,opt,name=stack_size,json=stackSize,proto3" json:"stack_size,omitempty"`
	LoadedSize uint64 `protobuf:"varint,3,opt,name=loaded_size,json=loadedSize,proto3" json:"loaded_size,omitempty"`
	LastErr    string `protobuf:"bytes,4,opt,name=last_err,json=lastErr,proto3" json:"last_err,omitempty"`
}

func (x *PreLoadTaskStatus) Reset() {
	*x = PreLoadTaskStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_src_turbo_turbo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreLoadTaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreLoadTaskStatus) ProtoMessage() {}

func (x *PreLoadTaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_turbo_turbo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreLoadTaskStatus.ProtoReflect.Descriptor instead.
func (*PreLoadTaskStatus) Descriptor() ([]byte, []int) {
	return file_proto_src_turbo_turbo_proto_rawDescGZIP(), []int{2}
}

func (x *PreLoadTaskStatus) GetStackId() uint64 {
	if x != nil {
		return x.StackId
	}
	return 0
}

func (x *PreLoadTaskStatus) GetStackSize() uint64 {
	if x != nil {
		return x.StackSize
	}
	return 0
}

func (x *PreLoadTaskStatus) GetLoadedSize() uint64 {
	if x != nil {
		return x.LoadedSize
	}
	return 0
}

func (x *PreLoadTaskStatus) GetLastErr() string {
	if x != nil {
		return x.LastErr
	}
	return ""
}

type MaintainResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TasksStatus []*PreLoadTaskStatus `protobuf:"bytes,1,rep,name=tasks_status,json=tasksStatus,proto3" json:"tasks_status,omitempty"`
}

func (x *MaintainResp) Reset() {
	*x = MaintainResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_src_turbo_turbo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaintainResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintainResp) ProtoMessage() {}

func (x *MaintainResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_turbo_turbo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintainResp.ProtoReflect.Descriptor instead.
func (*MaintainResp) Descriptor() ([]byte, []int) {
	return file_proto_src_turbo_turbo_proto_rawDescGZIP(), []int{3}
}

func (x *MaintainResp) GetTasksStatus() []*PreLoadTaskStatus {
	if x != nil {
		return x.TasksStatus
	}
	return nil
}

var File_proto_src_turbo_turbo_proto protoreflect.FileDescriptor

var file_proto_src_turbo_turbo_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x75, 0x72, 0x62,
	0x6f, 0x2f, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x75, 0x72, 0x62, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x2e, 0x4d, 0x61,
	0x69, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x12,
	0x28, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x68, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x4c, 0x6f, 0x61, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22,
	0x89, 0x01, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x22, 0x4b, 0x0a, 0x0c, 0x4d,
	0x61, 0x69, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0c, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x4c, 0x6f, 0x61,
	0x64, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x74, 0x61, 0x73,
	0x6b, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x3c, 0x0a, 0x05, 0x54, 0x75, 0x72, 0x62,
	0x6f, 0x12, 0x33, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x2e,
	0x74, 0x75, 0x72, 0x62, 0x6f, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x13, 0x2e, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x62, 0x79, 0x74, 0x65, 0x73, 0x74,
	0x61, 0x63, 0x6b, 0x2f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x3b, 0x74, 0x75,
	0x72, 0x62, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_src_turbo_turbo_proto_rawDescOnce sync.Once
	file_proto_src_turbo_turbo_proto_rawDescData = file_proto_src_turbo_turbo_proto_rawDesc
)

func file_proto_src_turbo_turbo_proto_rawDescGZIP() []byte {
	file_proto_src_turbo_turbo_proto_rawDescOnce.Do(func() {
		file_proto_src_turbo_turbo_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_src_turbo_turbo_proto_rawDescData)
	})
	return file_proto_src_turbo_turbo_proto_rawDescData
}

var file_proto_src_turbo_turbo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_src_turbo_turbo_proto_goTypes = []interface{}{
	(*MaintainReq)(nil),       // 0: turbo.MaintainReq
	(*PreLoadTask)(nil),       // 1: turbo.PreLoadTask
	(*PreLoadTaskStatus)(nil), // 2: turbo.PreLoadTaskStatus
	(*MaintainResp)(nil),      // 3: turbo.MaintainResp
	nil,                       // 4: turbo.MaintainReq.SecretsEntry
}
var file_proto_src_turbo_turbo_proto_depIdxs = []int32{
	4, // 0: turbo.MaintainReq.secrets:type_name -> turbo.MaintainReq.SecretsEntry
	1, // 1: turbo.MaintainReq.tasks:type_name -> turbo.PreLoadTask
	2, // 2: turbo.MaintainResp.tasks_status:type_name -> turbo.PreLoadTaskStatus
	0, // 3: turbo.Turbo.Maintain:input_type -> turbo.MaintainReq
	3, // 4: turbo.Turbo.Maintain:output_type -> turbo.MaintainResp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_src_turbo_turbo_proto_init() }
func file_proto_src_turbo_turbo_proto_init() {
	if File_proto_src_turbo_turbo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_src_turbo_turbo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaintainReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_src_turbo_turbo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreLoadTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_src_turbo_turbo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreLoadTaskStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_src_turbo_turbo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaintainResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_src_turbo_turbo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_src_turbo_turbo_proto_goTypes,
		DependencyIndexes: file_proto_src_turbo_turbo_proto_depIdxs,
		MessageInfos:      file_proto_src_turbo_turbo_proto_msgTypes,
	}.Build()
	File_proto_src_turbo_turbo_proto = out.File
	file_proto_src_turbo_turbo_proto_rawDesc = nil
	file_proto_src_turbo_turbo_proto_goTypes = nil
	file_proto_src_turbo_turbo_proto_depIdxs = nil
}
