# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controller.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\ncontroller\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n\x07StackID\x12\x10\n\x08stack_id\x18\x01 \x01(\x04\"2\n\x0bStackSource\x12\x10\n\x08stack_id\x18\x01 \x01(\x04\x12\x11\n\tlocations\x18\x02 \x03(\t\"4\n\x0e\x43\x61llPreLoadReq\x12\x10\n\x08stack_id\x18\x01 \x01(\x04\x12\x10\n\x08replicas\x18\x02 \x01(\x03\"\xc3\x01\n\x07PreLoad\x12\x10\n\x08stack_id\x18\x01 \x01(\x04\x12\'\n\x05state\x18\x02 \x01(\x0e\x32\x18.controller.PreLoadState\x12\x1a\n\x12\x63reation_timestamp\x18\x03 \x01(\x03\x12\x0f\n\x07\x62server\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\x04\x12\x0e\n\x06loaded\x18\x06 \x01(\x04\x12\x18\n\x10loaded_timestamp\x18\x07 \x01(\x03\x12\x18\n\x10update_timestamp\x18\x08 \x01(\x03\"\x9c\x01\n\x11PreLoadAssignment\x12\x10\n\x08stack_id\x18\x01 \x01(\x04\x12\x12\n\ntotal_size\x18\x02 \x01(\x04\x12\x0e\n\x06loaded\x18\x03 \x01(\x04\x12\x0f\n\x07\x62server\x18\x04 \x01(\t\x12\x11\n\tdata_addr\x18\x05 \x01(\t\x12\x1a\n\x12\x63reation_timestamp\x18\x06 \x01(\x03\x12\x11\n\terror_msg\x18\x07 \x01(\t\"E\n\x12PreLoadAssignments\x12/\n\x08preloads\x18\x01 \x03(\x0b\x32\x1d.controller.PreLoadAssignment*K\n\x0cPreLoadState\x12\x08\n\x04INIT\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x12\x0c\n\x08\x44\x45LETING\x10\x04\x32\xac\x03\n\nController\x12:\n\x0bNextStackID\x12\x16.google.protobuf.Empty\x1a\x13.controller.StackID\x12\x46\n\x13RegisterStackSource\x12\x17.controller.StackSource\x1a\x16.google.protobuf.Empty\x12H\n\x15\x44\x65RegisterStackSource\x12\x17.controller.StackSource\x1a\x16.google.protobuf.Empty\x12\x45\n\x15QueryRegisteredSource\x12\x13.controller.StackID\x1a\x17.controller.StackSource\x12\x45\n\x07PreLoad\x12\x1a.controller.CallPreLoadReq\x1a\x1e.controller.PreLoadAssignments\x12\x42\n\x0bLocateStack\x12\x13.controller.StackID\x1a\x1e.controller.PreLoadAssignmentsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRELOADSTATE']._serialized_start=624
  _globals['_PRELOADSTATE']._serialized_end=699
  _globals['_STACKID']._serialized_start=61
  _globals['_STACKID']._serialized_end=88
  _globals['_STACKSOURCE']._serialized_start=90
  _globals['_STACKSOURCE']._serialized_end=140
  _globals['_CALLPRELOADREQ']._serialized_start=142
  _globals['_CALLPRELOADREQ']._serialized_end=194
  _globals['_PRELOAD']._serialized_start=197
  _globals['_PRELOAD']._serialized_end=392
  _globals['_PRELOADASSIGNMENT']._serialized_start=395
  _globals['_PRELOADASSIGNMENT']._serialized_end=551
  _globals['_PRELOADASSIGNMENTS']._serialized_start=553
  _globals['_PRELOADASSIGNMENTS']._serialized_end=622
  _globals['_CONTROLLER']._serialized_start=702
  _globals['_CONTROLLER']._serialized_end=1130
# @@protoc_insertion_point(module_scope)
