// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.14.0
// source: proto/src/controller/controller.proto

package controller

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Controller_NextStackID_FullMethodName           = "/controller.Controller/NextStackID"
	Controller_RegisterStackSource_FullMethodName   = "/controller.Controller/RegisterStackSource"
	Controller_DeRegisterStackSource_FullMethodName = "/controller.Controller/DeRegisterStackSource"
	Controller_QueryRegisteredSource_FullMethodName = "/controller.Controller/QueryRegisteredSource"
	Controller_PreLoad_FullMethodName               = "/controller.Controller/PreLoad"
	Controller_LocateStack_FullMethodName           = "/controller.Controller/LocateStack"
)

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerClient interface {
	// NextStackID try to get next_stack id from controller.
	NextStackID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StackID, error)
	// RegisterStackSource register stack_id to source.
	RegisterStackSource(ctx context.Context, in *StackSource, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeRegisterStackSource deregister source from stack_id.
	DeRegisterStackSource(ctx context.Context, in *StackSource, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// QueryRegisteredSource query registered source.
	QueryRegisteredSource(ctx context.Context, in *StackID, opts ...grpc.CallOption) (*StackSource, error)
	// PreLoad help user to do preload or unpreload stack to bserver
	PreLoad(ctx context.Context, in *CallPreLoadReq, opts ...grpc.CallOption) (*PreLoadAssignments, error)
	// LocateStack help user find where the stack placed.
	LocateStack(ctx context.Context, in *StackID, opts ...grpc.CallOption) (*PreLoadAssignments, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) NextStackID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StackID, error) {
	out := new(StackID)
	err := c.cc.Invoke(ctx, Controller_NextStackID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) RegisterStackSource(ctx context.Context, in *StackSource, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Controller_RegisterStackSource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DeRegisterStackSource(ctx context.Context, in *StackSource, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Controller_DeRegisterStackSource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) QueryRegisteredSource(ctx context.Context, in *StackID, opts ...grpc.CallOption) (*StackSource, error) {
	out := new(StackSource)
	err := c.cc.Invoke(ctx, Controller_QueryRegisteredSource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) PreLoad(ctx context.Context, in *CallPreLoadReq, opts ...grpc.CallOption) (*PreLoadAssignments, error) {
	out := new(PreLoadAssignments)
	err := c.cc.Invoke(ctx, Controller_PreLoad_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) LocateStack(ctx context.Context, in *StackID, opts ...grpc.CallOption) (*PreLoadAssignments, error) {
	out := new(PreLoadAssignments)
	err := c.cc.Invoke(ctx, Controller_LocateStack_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility
type ControllerServer interface {
	// NextStackID try to get next_stack id from controller.
	NextStackID(context.Context, *emptypb.Empty) (*StackID, error)
	// RegisterStackSource register stack_id to source.
	RegisterStackSource(context.Context, *StackSource) (*emptypb.Empty, error)
	// DeRegisterStackSource deregister source from stack_id.
	DeRegisterStackSource(context.Context, *StackSource) (*emptypb.Empty, error)
	// QueryRegisteredSource query registered source.
	QueryRegisteredSource(context.Context, *StackID) (*StackSource, error)
	// PreLoad help user to do preload or unpreload stack to bserver
	PreLoad(context.Context, *CallPreLoadReq) (*PreLoadAssignments, error)
	// LocateStack help user find where the stack placed.
	LocateStack(context.Context, *StackID) (*PreLoadAssignments, error)
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (UnimplementedControllerServer) NextStackID(context.Context, *emptypb.Empty) (*StackID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextStackID not implemented")
}
func (UnimplementedControllerServer) RegisterStackSource(context.Context, *StackSource) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterStackSource not implemented")
}
func (UnimplementedControllerServer) DeRegisterStackSource(context.Context, *StackSource) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeRegisterStackSource not implemented")
}
func (UnimplementedControllerServer) QueryRegisteredSource(context.Context, *StackID) (*StackSource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRegisteredSource not implemented")
}
func (UnimplementedControllerServer) PreLoad(context.Context, *CallPreLoadReq) (*PreLoadAssignments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreLoad not implemented")
}
func (UnimplementedControllerServer) LocateStack(context.Context, *StackID) (*PreLoadAssignments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocateStack not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_NextStackID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).NextStackID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_NextStackID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).NextStackID(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_RegisterStackSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackSource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).RegisterStackSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_RegisterStackSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).RegisterStackSource(ctx, req.(*StackSource))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DeRegisterStackSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackSource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DeRegisterStackSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_DeRegisterStackSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DeRegisterStackSource(ctx, req.(*StackSource))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_QueryRegisteredSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).QueryRegisteredSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_QueryRegisteredSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).QueryRegisteredSource(ctx, req.(*StackID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_PreLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallPreLoadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).PreLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_PreLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).PreLoad(ctx, req.(*CallPreLoadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_LocateStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).LocateStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_LocateStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).LocateStack(ctx, req.(*StackID))
	}
	return interceptor(ctx, in, info, handler)
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controller.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NextStackID",
			Handler:    _Controller_NextStackID_Handler,
		},
		{
			MethodName: "RegisterStackSource",
			Handler:    _Controller_RegisterStackSource_Handler,
		},
		{
			MethodName: "DeRegisterStackSource",
			Handler:    _Controller_DeRegisterStackSource_Handler,
		},
		{
			MethodName: "QueryRegisteredSource",
			Handler:    _Controller_QueryRegisteredSource_Handler,
		},
		{
			MethodName: "PreLoad",
			Handler:    _Controller_PreLoad_Handler,
		},
		{
			MethodName: "LocateStack",
			Handler:    _Controller_LocateStack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/src/controller/controller.proto",
}
