# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import controller_pb2 as controller__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NextStackID = channel.unary_unary(
                '/controller.Controller/NextStackID',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=controller__pb2.StackID.FromString,
                _registered_method=True)
        self.RegisterStackSource = channel.unary_unary(
                '/controller.Controller/RegisterStackSource',
                request_serializer=controller__pb2.StackSource.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeRegisterStackSource = channel.unary_unary(
                '/controller.Controller/DeRegisterStackSource',
                request_serializer=controller__pb2.StackSource.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.QueryRegisteredSource = channel.unary_unary(
                '/controller.Controller/QueryRegisteredSource',
                request_serializer=controller__pb2.StackID.SerializeToString,
                response_deserializer=controller__pb2.StackSource.FromString,
                _registered_method=True)
        self.PreLoad = channel.unary_unary(
                '/controller.Controller/PreLoad',
                request_serializer=controller__pb2.CallPreLoadReq.SerializeToString,
                response_deserializer=controller__pb2.PreLoadAssignments.FromString,
                _registered_method=True)
        self.LocateStack = channel.unary_unary(
                '/controller.Controller/LocateStack',
                request_serializer=controller__pb2.StackID.SerializeToString,
                response_deserializer=controller__pb2.PreLoadAssignments.FromString,
                _registered_method=True)


class ControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NextStackID(self, request, context):
        """NextStackID try to get next_stack id from controller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterStackSource(self, request, context):
        """RegisterStackSource register stack_id to source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeRegisterStackSource(self, request, context):
        """DeRegisterStackSource deregister source from stack_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryRegisteredSource(self, request, context):
        """QueryRegisteredSource query registered source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreLoad(self, request, context):
        """PreLoad help user to do preload or unpreload stack to bserver
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocateStack(self, request, context):
        """LocateStack help user find where the stack placed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NextStackID': grpc.unary_unary_rpc_method_handler(
                    servicer.NextStackID,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=controller__pb2.StackID.SerializeToString,
            ),
            'RegisterStackSource': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterStackSource,
                    request_deserializer=controller__pb2.StackSource.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeRegisterStackSource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeRegisterStackSource,
                    request_deserializer=controller__pb2.StackSource.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'QueryRegisteredSource': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryRegisteredSource,
                    request_deserializer=controller__pb2.StackID.FromString,
                    response_serializer=controller__pb2.StackSource.SerializeToString,
            ),
            'PreLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.PreLoad,
                    request_deserializer=controller__pb2.CallPreLoadReq.FromString,
                    response_serializer=controller__pb2.PreLoadAssignments.SerializeToString,
            ),
            'LocateStack': grpc.unary_unary_rpc_method_handler(
                    servicer.LocateStack,
                    request_deserializer=controller__pb2.StackID.FromString,
                    response_serializer=controller__pb2.PreLoadAssignments.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('controller.Controller', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Controller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NextStackID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.Controller/NextStackID',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            controller__pb2.StackID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterStackSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.Controller/RegisterStackSource',
            controller__pb2.StackSource.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeRegisterStackSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.Controller/DeRegisterStackSource',
            controller__pb2.StackSource.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryRegisteredSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.Controller/QueryRegisteredSource',
            controller__pb2.StackID.SerializeToString,
            controller__pb2.StackSource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.Controller/PreLoad',
            controller__pb2.CallPreLoadReq.SerializeToString,
            controller__pb2.PreLoadAssignments.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LocateStack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.Controller/LocateStack',
            controller__pb2.StackID.SerializeToString,
            controller__pb2.PreLoadAssignments.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
